language: ruby
rvm:
- 1.9.3
script: bundle exec jekyll build
install: bundle install
after_success: bundle exec s3_website push
env:
  global:
  - secure: OjufYbKKlISS6aCEhMvqcV5Q1Ks1Qm2yJTrG6kI2zQxQN5WLEXIc26+fU6rdMoSaZQI0QUqglC3+XJtsAzJS1kQvFZm/zNBJN0Va/6mW2S/eQFm+LHkfBoVtLGCpIwF/gp05TdA9qhamMsrIwXJqWSdBM6/f140NvClCv5kLHP8=
  - secure: bmO5yeneut4LbQPoKr75nsdF+Crpa5pwnW0QAPHu26e7JCw7ghXx/tedCIOGxrIhUXqS3yRT4omLlh4JO/Nnn2lZBVR/637sMmlF5/NE5FrmL2UHn0v4JFmrA40Bryvf29d7Hp/9CeKmYCwjuSNDrqsBduJAiZ8FCOPfnlGk/QI=
